apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-service
  namespace: {{ .Values.namespace }}
  labels:
    {{ .Values.label }}
spec:
  type: NodePort
  ports:
  {{- range $port,$targetPort := .Values.container.port_map }}
  - name: tcp-{{ $targetPort }}
    port: {{ $port }}
    nodePort: 30080
    protocol: TCP
    targetPort: {{ $targetPort }}
  {{- end }} 
  selector:
    {{ .Values.label }}
