{{- $ns := .Values.namespace -}}
{{- $lb := .Values.label -}}
{{- range .Values.volumes }}
apiVersion: v1
kind: PersistentVolume
metadata: 
  name: {{ .name }}-pv
  namespace: {{ $ns }}
spec: 
  capacity:
    storage: {{ .size }} 
  accessModes: 
    - ReadWriteOnce
  hostPath:
    path: {{ .path }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: {{ .name }}-pvc
  namespace: {{ $ns }}
spec: 
  storageClassName: ""
  accessModes: 
    - ReadWriteOnce
  resources: 
    requests: 
      storage: {{ .size }}
---
{{- end }}
