{{- range .Values }}
  {{- $namespace := .namespace -}}
  {{- $label := .label -}}
  {{- range .volumes }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: {{ .name }}-pvc
spec: 
  accessModes: 
    - ReadWriteMany
  storageClassname: "" 
  resources: 
    requests: 
      storage: {{ .size }}
  selector:
    matchlabels:
      {{ $label }}
---
  {{- end }}
{{- end }}
