apiVersion: extensions/v1beta1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels: 
    {{ .Values.label }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{ .Values.label }}
  template:
    metadata:
      labels:
        {{ .Values.label }} 
    spec:
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.image }}
        env:
        {{- range $key, $value := .Values.container.env }}
          - name: {{ $key }}
            value: "{{ $value }}"
        {{- end }}
        volumeMounts:
        {{- range .Values.volumes }} 
        - name: {{ .name }}-storage
          mountPath: {{ .mount_path }}
        {{- end }}
        resources:
          limits:
            cpu: {{ default "1" .Values.container.resources.cpu_limits }}
            memory: {{ default "1G" .Values.container.resources.mem_limits }}
          requests:
            cpu: {{ default "200m" .Values.container.resources.cpu_requests }}
            memory: {{ default "1G" .Values.container.resources.mem_requests }}
        {{- range $key, $value := .Values.container.extra_opts }}
        {{ $key }}: "{{ $value }}" 
        {{- end }}
      volumes:
      {{- range .Values.volumes }}
      - name: {{ .name }}-storage
        persistentVolumeClaim:
          claimName: {{ .name }}-pvc
      {{- end }}
