{{- $ns := .Values.namespace -}}
{{- $lb := .Values.label -}}
{{- range .Values.volumes }}
apiVersion: v1
kind: PersistentVolume
metadata: 
  name: {{ .name }}-pv
  namespace: {{ $ns }}
  labels: 
    {{ $lb }}
spec: 
  capacity:
    storage: {{ .size }} 
  accessModes: 
    - ReadWriteMany
  nfs:
    path: "{{ .nfs.path }}"
    server: "{{ .nfs.server }}"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: {{ .name }}-pvc
  namespace: {{ $ns }}
spec: 
  accessModes: 
    - ReadWriteMany
  storageClassname: "" 
  resources: 
    requests: 
      storage: {{ .size }}
  selector:
    matchlabels:
      {{ $lb }}
---
{{- end }}
