all:
	helm package --debug blog
	#helm install /Users/shenlan/workspace/charts/charts-for-k8s/blog-0.0.2.tgz  --generate-name
	helm install /Users/shenlan/workspace/charts/charts-for-k8s/blog-0.0.2.tgz
