apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.svcName }}
  namespace: 
  labels:
    {{ .Values.label }}
spec:
  ports:
  - name: tcp-8081
    port: {{ .Values.svcPort }}
    protocol: TCP
    targetPort: 8081
  selector:
    {{ .Values.label }}
