{{- $ns := .Values.namespace -}}
{{- $lb := .Values.label -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: {{ .Values.svcName }}-pvc
spec: 
  accessModes: 
    - ReadWriteMany
  resources: 
    requests: 
      storage: {{ .Values.container.volumeSize }}
  selector:
    matchlabels:
      {{ $lb }}
# 现在平台不支持创建pv，只能手动创建
{{- if false -}}
---
apiVersion: v1
kind: PersistentVolume
metadata: 
  name: {{ .Values.svcName }}-pv
  labels:
    {{ .Values.label }}
spec: 
  accessModes: 
  - {{ .Values.volumes.accessModes }}
  capacity:
    storage: {{ .Values.container.volumeSize }}
  nfs:
    path: {{ .Values.volumes.nfs.path }}
    server: {{ .Values.volumes.nfs.server }}
  persistentVolumeReclaimPolicy: {{ .Values.volumes.persistentVolumeReclaimPolicy }}
{{- end -}}