apiVersion: v1
kind: PersistentVolume
metadata: 
  name: {{ .Values.name }}-pv
  namespace: {{ .Values.namespace }}
  labels:
    {{ .Values.label }}
spec: 
  capacity:
    storage: {{ .Values.storage.size }} 
  accessModes: 
    - ReadWriteMany
  hostPath:
    path: {{ .Values.volumes.host_path }}
