apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: {{ .Values.name }}-pvc
  namespace: default
spec: 
  accessModes: 
    - ReadWriteMany
  storageClassName: "" 
  resources: 
    requests: 
      storage: {{ .Values.storage.size }}
  selector:
    matchLabels:
      {{ .Values.label }} 
