apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-service
  namespace: {{ .Values.namespace }}
  labels:
    {{ .Values.label }}
spec:
  ports:
    - port: {{ .Values.service.port }}
  selector:
    {{ .Values.label }}
