name: jira
image: "jira:7.5.2"
label: "app: jira"
namespace: default

container:
  port_map:
    8080: 8080
  env:
    JAVA_OPTS: "-server -Xms800m -Xmx800m"
  resources:
    cpu_requests: 200m
    cpu_limits: 1
    mem_requests: 1G
    mem_limits: 1G

volumes:
  - name: jira-data
    size: 10Gi 
    nfs:
      path: "/datafs/jira"
      server: "192.168.3.220"
    mount_path: "/var/atlassian/jira"
  - name: jira-log
    size: 10Gi 
    nfs:
      path: "/datafs/jira"
      server: "192.168.3.220"
    mount_path: "/opt/atlassian/jira/logs"
