name: sonarqube
image: "sonarqube:7.1"
label: "app: sonarqube"
namespace: default

container:
  port_map:
    9000: 9000 
  env:
    SONARQUBE_JDBC_URL: "jdbc:postgresql://postgresql:5432/sona"
  resources:
    cpu_requests: 200m
    cpu_limits: 1
    mem_requests: 1G
    mem_limits: 1G

volumes:
  - name: sonarqube-data
    size: 10Gi
    nfs:
      path: "/datafs/sonarqube-data"
      server: "192.168.3.220"
    mount_path: "/opt/sonarqube/data"
  - name: sonrqube-extensions
    size: 10Gi
    nfs:
      path: "/datafs/sonarqube-extensions"
      server: "192.168.3.220"
    mount_path: "/opt/sonarqube/extensions"
