name: mysql-3
image: "mysql:5.6"
label: "app: mysql"
namespace: default

container:
  port_map:
    3306: 3306
  env:
    MYSQL_ROOT_PASSWORD: A4h3ljbn
  resources:
    cpu_requests: 200m
    cpu_limits: 1
    mem_requests: 1G
    mem_limits: 1G

volumes:
  - name: mysql-3
    size: 10Gi
    nfs:
      path: "/datafs/mysql"
      server: "192.168.3.220"
    mount_path: "/var/lib/mysql"
