name: redwood
image: "redwood:1.2.10"
label: "app: redwood"
namespace: default

container:
  port_map:
    3000: 3000
  env: 
    MONGO_HOST: 10.97.156.139
    MONGO_PORT: '27017'
  resources:
    cpu_requests: 200m
    cpu_limits: 1
    mem_requests: 1G
    mem_limits: 1G
  extra_opts:
    
volumes:
  - name: rewood
    size: 10Gi 
    host_path: "/datafs/redwood/"
    mount_path: "/RedwoodHQ/public/automationscripts"
